@url = http://localhost:8080

###

POST {{url}}/clothing_item HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "clothingType":"TESTTYPE",
    "clothingName":"TESTNAME",
    "clothingImage":"TESTIMAGE",
    "wearOnRainyDay":"yes",
    "wearOnHotDay":"yes"
}

###

DELETE {{url}}/api/locations/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

###

POST {{url}}/weather HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "latitude":"32",
    "longitude":"-117",
    "userId":"123"
}

###

GET @{{url}}/weather/66c3fdd7a8927f290ea3fda9 HTTP/1.1