@url = http://localhost:8080

GET http://localhost:8080/clothing_item/by_type?type=bottoms

###

GET http://localhost:8080/clothing_item/bottoms/66bebe26920f2f76cb568be0

###

GET http://localhost:8080/clothing_item/by_type?type=shoes

###

POST {{url}}/clothing_item HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "clothingType":"TESTTYPE",
    "clothingName":"TESTNAME",
    "clothingImage":"TESTIMAGE",
    "wearOnRainyDay":"yes",
    "wearOnHotDay":"yes"
}

###

DELETE {{url}}/api/locations/1 HTTP/1.1
Content-Type: application/json
Accept: application/json